apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- route.yaml
commonLabels:
  app: nextjs-app
  app.kubernetes.io/instance: nextjs-app-instance
  app.kubernetes.io/name: nextjs-app
images:
- name: quay.io/upslopeio/node-alpine
  newName: quay.io/an_qi_chen/nextjs-app
  newTag: 9bc496e40a0f38a7586bc41a7aa9b595ea39bdb9
